### ISSUE TITLE
Add icon to tree view

### ISSUE THREAD

**Issue by edahlseng** [jneuendorf/code-annotations#17]
It would be super helpful if the tree view could show which files have annotations in them currently!

**Comment by jneuendorf** [comment]
It seems it is not that easy to add more css classes to tree view entries.
Let's see what happens next: https://github.com/atom/tree-view/issues/1196

**Comment by jneuendorf** [comment]
Another possibility might be `tree-view`'s `entryForPath(entryPath)` API. Annotated files' entries could be manually traversed and modified. But that's probably way more error-prone (because `tree-view` would be unaware of the modifications which could result in losing the changes upon rerendering - basically the `react` argument) than providing an icon service.

**Comment by jneuendorf** [comment]
@edahlseng Hey, I just saw you recently [contributed](https://github.com/atom/tree-view/commit/f155e56919bcf5eeeb41700820f2ab2390cbbc96) to the `tree-view` package.
I guess you most likely know that package better than me - and since this issue has been created, some of their code has probably changed.

So do you have any ideas for solving this issue?
I would currently just try and see if consuming the service works together with `file-icons`.
If it doesn't I have no idea how to proceed...I've read through some `tree-view` and `file-icons` code but that hasn't really been enlightening 😕
