### ISSUE TITLE
Consider referencing comments by file + line number

### ISSUE THREAD

**Issue by edahlseng** [jneuendorf/code-annotations#18]
Interesting idea -- what if code-annotations referenced annotations based off a combination of file & line number rather than named comments? This would keep source code cleaner, would make it easier to perform other features (such as identifying all comments belonging to a file without needing to scan the file), and I suspect may be a bit more intuitive to use.

**Comment by edahlseng** [comment]
I'd love to try and get a rough prototype started for this. Thoughts? Would love to use this issue thread for discussion to bounce off ideas and get a better understanding of the best way to implement this.

**Comment by edahlseng** [comment]
Brain dump of some initial thoughts:
1. Could store the annotation metadata in a `.annotations.cson` file with the following structure:
```javascript
{
    "filename1.js": {
        "2": "annotation1.txt", // Describes an annotation on line 2 of filename1.js
        "17": "annotation2.txt", // Describes an annotation on line 17 of filename2.js
    }
}
```
2. Maybe each filename in the above structure should be a list instead of an object, in order to support multiple comments per line?
3. The annotation files could have randomly generated strings for the filename
4. On startup, we could check for a `.names.cson` file, and emit a warning saying that it should be converted to the new format

**Comment by jneuendorf** [comment]
### Concerning (1) and (4)
Agreed.

### Concerning (2)
Do I understand your idea correctly as that multiple pins in the gutter belong to a single line? Generally that would make sense but I guess it'd be difficult to display or manage those annotations. Do you have a use case for that? Since annotated contents can be pretty complex, wouldn't it be possible to have those multiple 'same-line-annotations' packed into a single annotation (e.g. HTML + base64 image)?

### Concerning (3)
I wouldn't randomly generate the filenames because if someone without Atom works on an annotated file it should be possible for that person to figure out what content was attached. That's why I used names in the current implementation.
In case we change the way annotations work according to **(2)** this argument would become irrelevant though. In that case annotations would be visible to Atom users only.
Maybe the filename could be generated like `filename + linenumber + randomSalt`.

**Comment by edahlseng** [comment]
### Concerning (2)
I don't have a use case, was just wondering if that was something that should be supported. Although, thinking about it now, it may be best to only allow one comment per line for now, and then can add support for that in the future if people really want/need it (though as you suggest, that likely won't be the case).

### Concerning (3)
That's a good point about supporting people who don't use Atom. If someone wants to move a comment, the filename would need to be renamed. But I guess I don't see that as a show-stopper.

**Comment by jneuendorf** [comment]
### Concerning (2)

Alright. So that's postponed for now.

### Concerning (3)

Maybe we could hash the line that's annotated instead of generating a random filename.
That way editing annotated files without Atom could be detected (and somehow fixed?) because the hashes would be invalid after editing. Since `filename` and `line number` are already encoded in the JSON's structure, the hash would suffice as filename (depending on non-Atom users should be able to find annotations or not).
That way the `// CODE-ANNOTATION: ...` comments could be dropped as you suggested earlier.

**Comment by edahlseng** [comment]
### Concerning (3)

What's the motivation for using hashes of the line contents as a file name? So that we can keep track of moving lines? I think that if a user is editing a file, then they'll be aware that comments could shift lines, but they will always be able to move those annotations as needed.

If the file names were based off of line numbers, then there's a possibility that we wouldn't need a `.annotations.cson` file to keep track of the files, we could instead just pull that information from the annotation file tree.

Then again, if we use filenames + line number as the filename for annotations, then that has the possibility of leading to extremely long filenames. We will want to use relative paths (that are then URI encoded or something similar) and if an annotated file lives several subfolders deep, then that name will become very long.

**Comment by jneuendorf** [comment]
### Concerning (3)

The more I think about it the more I feel like we shouldn't care too much about non-Atom users - at least for now. So hashing is unnecessary.

I think having a `.annotations.cson` isn't so bad.
That way only one file has to be read (less IO than reading a potentially large file tree).
Also URI encoding wouldn't be required as the paths would just be strings. I don't know how Atom handles paths but I guess Windows should be supported (`/` vs`\`).
Furthermore, the length of the path doesn't matter - maybe too long paths in a filename could exceed the maximum filename length.

**Comment by jneuendorf** [comment]
@edahlseng Hey, sorry for the long inactivity. Have you started any local work? If not I would go ahead myself.

**Comment by edahlseng** [comment]
Hey @jneuendorf, unfortunately I don't have anything started. As is typical, I got caught up with work and haven't found the time to set aside for this 😕.

**Comment by jneuendorf** [comment]
Hey @edahlseng, no problem. I just wanted to make sure no work was done for nothing. 😉

**Comment by jneuendorf** [comment]
FYI: Branch for this issue is `issue_18`.

**Comment by jneuendorf** [comment]
Work is done here. Remaining bugs where added to #21.
